# Change these first
owner: k-safe # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Busby Main Site
    url: $BUSBY_URL
  - name: Busby Insights
    url: $INSIGHTS_URL
  - name: Busby Ideas
    url: $IDEAS_URL
  - name: Busby Partner Portal
    url: $PARTNER_URL
  - name: Busby Support
    url: $SUPPORT_URL
  - name: Busby Marketplace
    url: $MARKETPLACE_URL
  # - name: Test Busby Broken Site
  #  url: https://thissitedoesnotexist.koj.co

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status1.busby.io
  # baseUrl: /your-repo-name
  logoUrl: https://activate.busby.io/static/media/busby-logo-black.2ce4b36e.png
  name: Busby Status
  introTitle: "This is uptime monitor and status page for Busby, created by K-Safe."
  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/k-safe/upptime). 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
