owner: k-safe # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Flare Main Site
    url: $FLARE_URL
  - name: Flare Insights
    url: $INSIGHTS_URL
  - name: Flare Ideas
    url: $IDEAS_URL
  - name: Flare Partner Portal
    url: $PARTNER_URL
  - name: Flare Support
    url: $SUPPORT_URL
    expectedStatusCodes:
      - 200
      - 403
  - name: Flare Marketplace
    url: $MARKETPLACE_URL
  #- name: Vault
  #  url: $VAULT_URL
  # - name: Test Busby Broken Site
  #  url: https://thissitedoesnotexist.koj.co

status-website:
  cname: status.flaresafety.com
  logoUrl: $LOGO_URL
  favicon: $FAVICON_URL
  name: Flare Status
  introTitle: "This is the uptime monitor and status page for Flare by K-Safe."
  introMessage: This is a status page which uses **real-time** data from our GitHub repository. 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
